# workflows:
#   flutter-workflow:
#     name: Flutter CI/CD Pipeline
#     max_build_duration: 90 # زيادة الحد الأقصى للوقت إلى 90 دقيقة
#     environment:
#       flutter: stable # تثبيت إصدار Flutter مستقر
#       vars:
#         CI: true
#     scripts:
#       - name: Install dependencies
#         script: flutter pub get || echo "Dependencies installation failed, skipping..."
#       - name: Analyze code (optional, won't fail)
#         script: |
#           flutter analyze || echo "Code analysis failed, ignoring..."
#       - name: Run tests (optional, won't fail)
#         script: |
#           flutter test || echo "Some tests failed, skipping..."
#       - name: Build debug APK (optional)
#         script: |
#           flutter build apk --debug || echo "Build failed, skipping..."

workflows:
  automated-testing:
    name: Automated Testing
    max_build_duration: 120 # وقت كافي (ساعتين)
    environment:
      flutter: stable # يستخدم نسخة Flutter المستقرة
      vars:
        CI: true
    scripts:
      - name: Install dependencies
        script: |
          echo "Step 1: Installing dependencies..."
          flutter pub get

      - name: Analyze code
        script: |
          echo "Step 2: Analyzing code..."
          flutter analyze || error_count=$((error_count+1)) && echo "Code analysis failed, continuing..."

      - name: Run tests
        script: |
          echo "Step 3: Running unit tests..."
          flutter test || error_count=$((error_count+1)) && echo "Unit tests failed, continuing..."

      - name: Build debug APK
        script: |
          echo "Step 4: Building debug APK..."
          flutter clean # تنظيف المشروع قبل البناء
          flutter build apk --debug || { echo "Build failed"; error_count=$((error_count+1)); }

      - name: Report errors
        script: |
          echo "Total errors encountered: $error_count"

artifacts:
  - build/app/outputs/flutter-apk/app-debug.apk # حفظ APK الناتج
