workflows:
  flutter-workflow:
    name: Flutter CI/CD Pipeline
    max_build_duration: 60 # الحد الأقصى للوقت (بالدقائق)
    environment:
      flutter: stable # تثبيت إصدار Flutter مستقر
      vars:
        CI: true
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Analyze code
        script: flutter analyze
      - name: Run tests
        script: flutter test
    artifacts:
      - build/**/outputs/**/*.apk # رفع ملفات APK بعد البناء (اختياري)
      - build/**/outputs/**/*.aab # رفع ملفات AAB بعد البناء (اختياري)
