name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout الكود
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. إعداد Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. تحديث Dart SDK (إذا لم يكن مثبتًا أو كان قديمًا)
      - name: Install Dart SDK 3.6.0+
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/stable-release.pub.gpg | apt-key add -'
          sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/stable_release-archive-keyring.gpg | apt-key add -'
          sudo apt-get update -y
          sudo apt-get install dart

      # 4. تثبيت Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'  # تأكد من أن هذه النسخة تدعم Dart 3.6.0+

      # 5. إضافة خطوة flutter doctor للتحقق من الإصدارات
      - name: Check Flutter & Dart Versions
        run: |
          flutter doctor -v

      # 6. تثبيت التبعيات
      - name: Install dependencies
        run: flutter pub get

      # 7. تشغيل الاختبارات
      - name: Run tests
        run: flutter test --no-pub

      # 8. بناء الـ APK
      - name: Build APK
        run: flutter build apk --release

      # 9. رفع الـ APK
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
