name: Dart Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"  # تأكد من أن هذا الإصدار حديث

      - name: Verify Flutter installation
        run: flutter --version  # يعرض إصدار Flutter و Dart للتأكد

      - name: Upgrade Flutter SDK
        run: flutter upgrade  # يضمن أن لديك أحدث نسخة

      - name: Check Dart version
        run: dart --version  # تأكد من أن Dart هو 3.2.3 أو أحدث

      - name: Get dependencies
        run: flutter pub get

      - name: Upgrade dependencies (اختياري)
        run: flutter pub upgrade

      - name: Run tests
        run: flutter test
