name: Flutter Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'  # تأكد من أنك تستخدم إصدار يحتوي على Dart SDK 3.2.3 أو أعلى

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
