name: Dart Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Dart
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      # 3. Install dependencies
      - name: Get dependencies
        run: dart pub get

      # 4. Run tests
      - name: Run tests
        run: dart test
