name: Dart Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '>=3.2.3 <4.0.0'  # تحديث النسخة المطلوبة من Dart SDK

      - name: Get dependencies
        run: dart pub get

      - name: Run tests
        run: dart test
